/*
 * Copyright (c) 2015 by Evernote Corporation, All rights reserved.
 *
 * Use of the source code and binary libraries included in this package
 * is permitted under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "ENTProtocol.h"
#import "ENTException.h"
#import "FATObject.h"
#import "EDAMLimits.h"

#import "EDAMTypes.h"

@implementation EDAMData

+ (NSString *) structName {
  return @"Data";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BINARY optional:YES name:@"bodyHash"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:YES name:@"size"],
        [FATField fieldWithIndex:3 type:TType_BINARY optional:YES name:@"body"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMUserAttributes

+ (NSString *) structName {
  return @"UserAttributes";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"defaultLocationName"],
        [FATField fieldWithIndex:2 type:TType_DOUBLE optional:YES name:@"defaultLatitude"],
        [FATField fieldWithIndex:3 type:TType_DOUBLE optional:YES name:@"defaultLongitude"],
        [FATField fieldWithIndex:4 type:TType_BOOL optional:YES name:@"preactivation"],
        [FATField fieldWithIndex:5 type:TType_LIST optional:YES name:@"viewedPromotions" valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"incomingEmailAddress"],
        [FATField fieldWithIndex:7 type:TType_LIST optional:YES name:@"recentMailedAddresses" valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"comments"],
        [FATField fieldWithIndex:11 type:TType_I64 optional:YES name:@"dateAgreedToTermsOfService"],
        [FATField fieldWithIndex:12 type:TType_I32 optional:YES name:@"maxReferrals"],
        [FATField fieldWithIndex:13 type:TType_I32 optional:YES name:@"referralCount"],
        [FATField fieldWithIndex:14 type:TType_STRING optional:YES name:@"refererCode"],
        [FATField fieldWithIndex:15 type:TType_I64 optional:YES name:@"sentEmailDate"],
        [FATField fieldWithIndex:16 type:TType_I32 optional:YES name:@"sentEmailCount"],
        [FATField fieldWithIndex:17 type:TType_I32 optional:YES name:@"dailyEmailLimit"],
        [FATField fieldWithIndex:18 type:TType_I64 optional:YES name:@"emailOptOutDate"],
        [FATField fieldWithIndex:19 type:TType_I64 optional:YES name:@"partnerEmailOptInDate"],
        [FATField fieldWithIndex:20 type:TType_STRING optional:YES name:@"preferredLanguage"],
        [FATField fieldWithIndex:21 type:TType_STRING optional:YES name:@"preferredCountry"],
        [FATField fieldWithIndex:22 type:TType_BOOL optional:YES name:@"clipFullPage"],
        [FATField fieldWithIndex:23 type:TType_STRING optional:YES name:@"twitterUserName"],
        [FATField fieldWithIndex:24 type:TType_STRING optional:YES name:@"twitterId"],
        [FATField fieldWithIndex:25 type:TType_STRING optional:YES name:@"groupName"],
        [FATField fieldWithIndex:26 type:TType_STRING optional:YES name:@"recognitionLanguage"],
        [FATField fieldWithIndex:28 type:TType_STRING optional:YES name:@"referralProof"],
        [FATField fieldWithIndex:29 type:TType_BOOL optional:YES name:@"educationalDiscount"],
        [FATField fieldWithIndex:30 type:TType_STRING optional:YES name:@"businessAddress"],
        [FATField fieldWithIndex:31 type:TType_BOOL optional:YES name:@"hideSponsorBilling"],
        [FATField fieldWithIndex:32 type:TType_BOOL optional:YES name:@"taxExempt"],
        [FATField fieldWithIndex:33 type:TType_BOOL optional:YES name:@"useEmailAutoFiling"],
        [FATField fieldWithIndex:34 type:TType_I32 optional:YES name:@"reminderEmailConfig"],
        [FATField fieldWithIndex:35 type:TType_I64 optional:YES name:@"emailAddressLastConfirmed"],
        [FATField fieldWithIndex:36 type:TType_I64 optional:YES name:@"passwordUpdated"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBusinessUserAttributes

+ (NSString *) structName {
  return @"BusinessUserAttributes";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"title"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"location"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"department"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"mobilePhone"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"linkedInProfileUrl"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"workPhone"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"companyStartDate"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAccounting

+ (NSString *) structName {
  return @"Accounting";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:YES name:@"uploadLimit"],
        [FATField fieldWithIndex:2 type:TType_I64 optional:YES name:@"uploadLimitEnd"],
        [FATField fieldWithIndex:3 type:TType_I64 optional:YES name:@"uploadLimitNextMonth"],
        [FATField fieldWithIndex:4 type:TType_I32 optional:YES name:@"premiumServiceStatus"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"premiumOrderNumber"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"premiumCommerceService"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"premiumServiceStart"],
        [FATField fieldWithIndex:8 type:TType_STRING optional:YES name:@"premiumServiceSKU"],
        [FATField fieldWithIndex:9 type:TType_I64 optional:YES name:@"lastSuccessfulCharge"],
        [FATField fieldWithIndex:10 type:TType_I64 optional:YES name:@"lastFailedCharge"],
        [FATField fieldWithIndex:11 type:TType_STRING optional:YES name:@"lastFailedChargeReason"],
        [FATField fieldWithIndex:12 type:TType_I64 optional:YES name:@"nextPaymentDue"],
        [FATField fieldWithIndex:13 type:TType_I64 optional:YES name:@"premiumLockUntil"],
        [FATField fieldWithIndex:14 type:TType_I64 optional:YES name:@"updated"],
        [FATField fieldWithIndex:16 type:TType_STRING optional:YES name:@"premiumSubscriptionNumber"],
        [FATField fieldWithIndex:17 type:TType_I64 optional:YES name:@"lastRequestedCharge"],
        [FATField fieldWithIndex:18 type:TType_STRING optional:YES name:@"currency"],
        [FATField fieldWithIndex:19 type:TType_I32 optional:YES name:@"unitPrice"],
        [FATField fieldWithIndex:20 type:TType_I32 optional:YES name:@"businessId"],
        [FATField fieldWithIndex:21 type:TType_STRING optional:YES name:@"businessName"],
        [FATField fieldWithIndex:22 type:TType_I32 optional:YES name:@"businessRole"],
        [FATField fieldWithIndex:23 type:TType_I32 optional:YES name:@"unitDiscount"],
        [FATField fieldWithIndex:24 type:TType_I64 optional:YES name:@"nextChargeDate"],
        [FATField fieldWithIndex:25 type:TType_I32 optional:YES name:@"availablePoints"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBusinessUserInfo

+ (NSString *) structName {
  return @"BusinessUserInfo";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"businessId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"businessName"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"role"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"email"],
        [FATField fieldWithIndex:5 type:TType_I64 optional:YES name:@"updated"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMPremiumInfo

+ (NSString *) structName {
  return @"PremiumInfo";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:NO name:@"currentTime"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:NO name:@"premium"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:NO name:@"premiumRecurring"],
        [FATField fieldWithIndex:4 type:TType_I64 optional:YES name:@"premiumExpirationDate"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:NO name:@"premiumExtendable"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:NO name:@"premiumPending"],
        [FATField fieldWithIndex:7 type:TType_BOOL optional:NO name:@"premiumCancellationPending"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:NO name:@"canPurchaseUploadAllowance"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"sponsoredGroupName"],
        [FATField fieldWithIndex:10 type:TType_I32 optional:YES name:@"sponsoredGroupRole"],
        [FATField fieldWithIndex:11 type:TType_BOOL optional:YES name:@"premiumUpgradable"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMUser

+ (NSString *) structName {
  return @"User";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"id"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"username"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"email"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"timezone"],
        [FATField fieldWithIndex:7 type:TType_I32 optional:YES name:@"privilege"],
        [FATField fieldWithIndex:9 type:TType_I64 optional:YES name:@"created"],
        [FATField fieldWithIndex:10 type:TType_I64 optional:YES name:@"updated"],
        [FATField fieldWithIndex:11 type:TType_I64 optional:YES name:@"deleted"],
        [FATField fieldWithIndex:13 type:TType_BOOL optional:YES name:@"active"],
        [FATField fieldWithIndex:14 type:TType_STRING optional:YES name:@"shardId"],
        [FATField fieldWithIndex:15 type:TType_STRUCT optional:YES name:@"attributes" valueType:TType_STRUCT valueClass:[EDAMUserAttributes class]],
        [FATField fieldWithIndex:16 type:TType_STRUCT optional:YES name:@"accounting" valueType:TType_STRUCT valueClass:[EDAMAccounting class]],
        [FATField fieldWithIndex:17 type:TType_STRUCT optional:YES name:@"premiumInfo" valueType:TType_STRUCT valueClass:[EDAMPremiumInfo class]],
        [FATField fieldWithIndex:18 type:TType_STRUCT optional:YES name:@"businessUserInfo" valueType:TType_STRUCT valueClass:[EDAMBusinessUserInfo class]],
        [FATField fieldWithIndex:19 type:TType_STRING optional:YES name:@"photoUrl"],
        [FATField fieldWithIndex:20 type:TType_I64 optional:YES name:@"photoLastUpdated"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMContact

+ (NSString *) structName {
  return @"Contact";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"id"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"type"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"photoUrl"],
        [FATField fieldWithIndex:5 type:TType_I64 optional:YES name:@"photoLastUpdated"],
        [FATField fieldWithIndex:6 type:TType_BINARY optional:YES name:@"messagingPermit"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"messagingPermitExpires"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMIdentity

+ (NSString *) structName {
  return @"Identity";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:NO name:@"id"],
        [FATField fieldWithIndex:2 type:TType_STRUCT optional:YES name:@"contact" valueType:TType_STRUCT valueClass:[EDAMContact class]],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"userId"],
        [FATField fieldWithIndex:4 type:TType_BOOL optional:YES name:@"deactivated"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:YES name:@"sameBusiness"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:YES name:@"blocked"],
        [FATField fieldWithIndex:7 type:TType_BOOL optional:YES name:@"userConnected"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMTag

+ (NSString *) structName {
  return @"Tag";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"parentGuid"],
        [FATField fieldWithIndex:4 type:TType_I32 optional:YES name:@"updateSequenceNum"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMLazyMap

+ (NSString *) structName {
  return @"LazyMap";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_SET optional:YES name:@"keysOnly" valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:2 type:TType_MAP optional:YES name:@"fullMap" keyType:TType_STRING keyClass:NULL valueType:TType_STRING valueClass:NULL],
    ];
  }
  return structFields;
}

@end

@implementation EDAMResourceAttributes

+ (NSString *) structName {
  return @"ResourceAttributes";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"sourceURL"],
        [FATField fieldWithIndex:2 type:TType_I64 optional:YES name:@"timestamp"],
        [FATField fieldWithIndex:3 type:TType_DOUBLE optional:YES name:@"latitude"],
        [FATField fieldWithIndex:4 type:TType_DOUBLE optional:YES name:@"longitude"],
        [FATField fieldWithIndex:5 type:TType_DOUBLE optional:YES name:@"altitude"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"cameraMake"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"cameraModel"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"clientWillIndex"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"recoType"],
        [FATField fieldWithIndex:10 type:TType_STRING optional:YES name:@"fileName"],
        [FATField fieldWithIndex:11 type:TType_BOOL optional:YES name:@"attachment"],
        [FATField fieldWithIndex:12 type:TType_STRUCT optional:YES name:@"applicationData" valueType:TType_STRUCT valueClass:[EDAMLazyMap class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMResource

+ (NSString *) structName {
  return @"Resource";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"noteGuid"],
        [FATField fieldWithIndex:3 type:TType_STRUCT optional:YES name:@"data" valueType:TType_STRUCT valueClass:[EDAMData class]],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"mime"],
        [FATField fieldWithIndex:5 type:TType_I16 optional:YES name:@"width"],
        [FATField fieldWithIndex:6 type:TType_I16 optional:YES name:@"height"],
        [FATField fieldWithIndex:7 type:TType_I16 optional:YES name:@"duration"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"active"],
        [FATField fieldWithIndex:9 type:TType_STRUCT optional:YES name:@"recognition" valueType:TType_STRUCT valueClass:[EDAMData class]],
        [FATField fieldWithIndex:11 type:TType_STRUCT optional:YES name:@"attributes" valueType:TType_STRUCT valueClass:[EDAMResourceAttributes class]],
        [FATField fieldWithIndex:12 type:TType_I32 optional:YES name:@"updateSequenceNum"],
        [FATField fieldWithIndex:13 type:TType_STRUCT optional:YES name:@"alternateData" valueType:TType_STRUCT valueClass:[EDAMData class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNoteAttributes

+ (NSString *) structName {
  return @"NoteAttributes";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:YES name:@"subjectDate"],
        [FATField fieldWithIndex:10 type:TType_DOUBLE optional:YES name:@"latitude"],
        [FATField fieldWithIndex:11 type:TType_DOUBLE optional:YES name:@"longitude"],
        [FATField fieldWithIndex:12 type:TType_DOUBLE optional:YES name:@"altitude"],
        [FATField fieldWithIndex:13 type:TType_STRING optional:YES name:@"author"],
        [FATField fieldWithIndex:14 type:TType_STRING optional:YES name:@"source"],
        [FATField fieldWithIndex:15 type:TType_STRING optional:YES name:@"sourceURL"],
        [FATField fieldWithIndex:16 type:TType_STRING optional:YES name:@"sourceApplication"],
        [FATField fieldWithIndex:17 type:TType_I64 optional:YES name:@"shareDate"],
        [FATField fieldWithIndex:18 type:TType_I64 optional:YES name:@"reminderOrder"],
        [FATField fieldWithIndex:19 type:TType_I64 optional:YES name:@"reminderDoneTime"],
        [FATField fieldWithIndex:20 type:TType_I64 optional:YES name:@"reminderTime"],
        [FATField fieldWithIndex:21 type:TType_STRING optional:YES name:@"placeName"],
        [FATField fieldWithIndex:22 type:TType_STRING optional:YES name:@"contentClass"],
        [FATField fieldWithIndex:23 type:TType_STRUCT optional:YES name:@"applicationData" valueType:TType_STRUCT valueClass:[EDAMLazyMap class]],
        [FATField fieldWithIndex:24 type:TType_STRING optional:YES name:@"lastEditedBy"],
        [FATField fieldWithIndex:26 type:TType_MAP optional:YES name:@"classifications" keyType:TType_STRING keyClass:NULL valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:27 type:TType_I32 optional:YES name:@"creatorId"],
        [FATField fieldWithIndex:28 type:TType_I32 optional:YES name:@"lastEditorId"],
        [FATField fieldWithIndex:29 type:TType_BOOL optional:YES name:@"sharedWithBusiness"],
        [FATField fieldWithIndex:30 type:TType_STRING optional:YES name:@"conflictSourceNoteGuid"],
        [FATField fieldWithIndex:31 type:TType_I32 optional:YES name:@"noteTitleQuality"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSharedNote

+ (NSString *) structName {
  return @"SharedNote";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"sharerUserID"],
        [FATField fieldWithIndex:2 type:TType_STRUCT optional:YES name:@"recipientIdentity" valueType:TType_STRUCT valueClass:[EDAMIdentity class]],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"privilege"],
        [FATField fieldWithIndex:4 type:TType_I64 optional:YES name:@"serviceCreated"],
        [FATField fieldWithIndex:5 type:TType_I64 optional:YES name:@"serviceUpdated"],
        [FATField fieldWithIndex:6 type:TType_I64 optional:YES name:@"serviceAssigned"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNoteRestrictions

+ (NSString *) structName {
  return @"NoteRestrictions";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BOOL optional:YES name:@"noUpdateTitle"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:YES name:@"noUpdateContent"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"noEmail"],
        [FATField fieldWithIndex:4 type:TType_BOOL optional:YES name:@"noShare"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:YES name:@"noSharePublicly"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNote

+ (NSString *) structName {
  return @"Note";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"title"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"content"],
        [FATField fieldWithIndex:4 type:TType_BINARY optional:YES name:@"contentHash"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"contentLength"],
        [FATField fieldWithIndex:6 type:TType_I64 optional:YES name:@"created"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"updated"],
        [FATField fieldWithIndex:8 type:TType_I64 optional:YES name:@"deleted"],
        [FATField fieldWithIndex:9 type:TType_BOOL optional:YES name:@"active"],
        [FATField fieldWithIndex:10 type:TType_I32 optional:YES name:@"updateSequenceNum"],
        [FATField fieldWithIndex:11 type:TType_STRING optional:YES name:@"notebookGuid"],
        [FATField fieldWithIndex:12 type:TType_LIST optional:YES name:@"tagGuids" valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:13 type:TType_LIST optional:YES name:@"resources" valueType:TType_STRUCT valueClass:[EDAMResource class]],
        [FATField fieldWithIndex:14 type:TType_STRUCT optional:YES name:@"attributes" valueType:TType_STRUCT valueClass:[EDAMNoteAttributes class]],
        [FATField fieldWithIndex:15 type:TType_LIST optional:YES name:@"tagNames" valueType:TType_STRING valueClass:NULL],
        [FATField fieldWithIndex:16 type:TType_LIST optional:YES name:@"sharedNotes" valueType:TType_STRUCT valueClass:[EDAMSharedNote class]],
        [FATField fieldWithIndex:17 type:TType_STRUCT optional:YES name:@"restrictions" valueType:TType_STRUCT valueClass:[EDAMNoteRestrictions class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMPublishing

+ (NSString *) structName {
  return @"Publishing";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"uri"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:YES name:@"order"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"ascending"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"publicDescription"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBusinessNotebook

+ (NSString *) structName {
  return @"BusinessNotebook";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"notebookDescription"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:YES name:@"privilege"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"recommended"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSavedSearchScope

+ (NSString *) structName {
  return @"SavedSearchScope";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BOOL optional:YES name:@"includeAccount"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:YES name:@"includePersonalLinkedNotebooks"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"includeBusinessLinkedNotebooks"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSavedSearch

+ (NSString *) structName {
  return @"SavedSearch";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"query"],
        [FATField fieldWithIndex:4 type:TType_I32 optional:YES name:@"format"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"updateSequenceNum"],
        [FATField fieldWithIndex:6 type:TType_STRUCT optional:YES name:@"scope" valueType:TType_STRUCT valueClass:[EDAMSavedSearchScope class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAd

+ (NSString *) structName {
  return @"Ad";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"id"],
        [FATField fieldWithIndex:2 type:TType_I16 optional:YES name:@"width"],
        [FATField fieldWithIndex:3 type:TType_I16 optional:YES name:@"height"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"advertiserName"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"imageUrl"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"destinationUrl"],
        [FATField fieldWithIndex:7 type:TType_I16 optional:YES name:@"displaySeconds"],
        [FATField fieldWithIndex:8 type:TType_DOUBLE optional:YES name:@"score"],
        [FATField fieldWithIndex:9 type:TType_BINARY optional:YES name:@"image"],
        [FATField fieldWithIndex:10 type:TType_STRING optional:YES name:@"imageMime"],
        [FATField fieldWithIndex:11 type:TType_STRING optional:YES name:@"html"],
        [FATField fieldWithIndex:12 type:TType_DOUBLE optional:YES name:@"displayFrequency"],
        [FATField fieldWithIndex:13 type:TType_BOOL optional:YES name:@"openInTrunk"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSharedNotebookRecipientSettings

+ (NSString *) structName {
  return @"SharedNotebookRecipientSettings";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BOOL optional:YES name:@"reminderNotifyEmail"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:YES name:@"reminderNotifyInApp"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNotebookRecipientSettings

+ (NSString *) structName {
  return @"NotebookRecipientSettings";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BOOL optional:YES name:@"reminderNotifyEmail"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:YES name:@"reminderNotifyInApp"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"inMyList"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSharedNotebook

+ (NSString *) structName {
  return @"SharedNotebook";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:YES name:@"id"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:YES name:@"userId"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"notebookGuid"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"email"],
        [FATField fieldWithIndex:18 type:TType_I64 optional:YES name:@"recipientIdentityId"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:YES name:@"notebookModifiable"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:YES name:@"requireLogin"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"serviceCreated"],
        [FATField fieldWithIndex:10 type:TType_I64 optional:YES name:@"serviceUpdated"],
        [FATField fieldWithIndex:8 type:TType_STRING optional:YES name:@"globalId"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"username"],
        [FATField fieldWithIndex:11 type:TType_I32 optional:YES name:@"privilege"],
        [FATField fieldWithIndex:12 type:TType_BOOL optional:YES name:@"allowPreview"],
        [FATField fieldWithIndex:13 type:TType_STRUCT optional:YES name:@"recipientSettings" valueType:TType_STRUCT valueClass:[EDAMSharedNotebookRecipientSettings class]],
        [FATField fieldWithIndex:14 type:TType_I32 optional:YES name:@"sharerUserId"],
        [FATField fieldWithIndex:15 type:TType_STRING optional:YES name:@"recipientUsername"],
        [FATField fieldWithIndex:17 type:TType_I32 optional:YES name:@"recipientUserId"],
        [FATField fieldWithIndex:16 type:TType_I64 optional:YES name:@"serviceAssigned"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNotebookRestrictions

+ (NSString *) structName {
  return @"NotebookRestrictions";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BOOL optional:YES name:@"noReadNotes"],
        [FATField fieldWithIndex:2 type:TType_BOOL optional:YES name:@"noCreateNotes"],
        [FATField fieldWithIndex:3 type:TType_BOOL optional:YES name:@"noUpdateNotes"],
        [FATField fieldWithIndex:4 type:TType_BOOL optional:YES name:@"noExpungeNotes"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:YES name:@"noShareNotes"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:YES name:@"noEmailNotes"],
        [FATField fieldWithIndex:7 type:TType_BOOL optional:YES name:@"noSendMessageToRecipients"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"noUpdateNotebook"],
        [FATField fieldWithIndex:9 type:TType_BOOL optional:YES name:@"noExpungeNotebook"],
        [FATField fieldWithIndex:10 type:TType_BOOL optional:YES name:@"noSetDefaultNotebook"],
        [FATField fieldWithIndex:11 type:TType_BOOL optional:YES name:@"noSetNotebookStack"],
        [FATField fieldWithIndex:12 type:TType_BOOL optional:YES name:@"noPublishToPublic"],
        [FATField fieldWithIndex:13 type:TType_BOOL optional:YES name:@"noPublishToBusinessLibrary"],
        [FATField fieldWithIndex:14 type:TType_BOOL optional:YES name:@"noCreateTags"],
        [FATField fieldWithIndex:15 type:TType_BOOL optional:YES name:@"noUpdateTags"],
        [FATField fieldWithIndex:16 type:TType_BOOL optional:YES name:@"noExpungeTags"],
        [FATField fieldWithIndex:17 type:TType_BOOL optional:YES name:@"noSetParentTag"],
        [FATField fieldWithIndex:18 type:TType_BOOL optional:YES name:@"noCreateSharedNotebooks"],
        [FATField fieldWithIndex:19 type:TType_I32 optional:YES name:@"updateWhichSharedNotebookRestrictions"],
        [FATField fieldWithIndex:20 type:TType_I32 optional:YES name:@"expungeWhichSharedNotebookRestrictions"],
        [FATField fieldWithIndex:21 type:TType_BOOL optional:YES name:@"noShareNotesWithBusiness"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNotebook

+ (NSString *) structName {
  return @"Notebook";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"updateSequenceNum"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:YES name:@"defaultNotebook"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"serviceCreated"],
        [FATField fieldWithIndex:8 type:TType_I64 optional:YES name:@"serviceUpdated"],
        [FATField fieldWithIndex:10 type:TType_STRUCT optional:YES name:@"publishing" valueType:TType_STRUCT valueClass:[EDAMPublishing class]],
        [FATField fieldWithIndex:11 type:TType_BOOL optional:YES name:@"published"],
        [FATField fieldWithIndex:12 type:TType_STRING optional:YES name:@"stack"],
        [FATField fieldWithIndex:13 type:TType_LIST optional:YES name:@"sharedNotebookIds" valueType:TType_I64 valueClass:NULL],
        [FATField fieldWithIndex:14 type:TType_LIST optional:YES name:@"sharedNotebooks" valueType:TType_STRUCT valueClass:[EDAMSharedNotebook class]],
        [FATField fieldWithIndex:15 type:TType_STRUCT optional:YES name:@"businessNotebook" valueType:TType_STRUCT valueClass:[EDAMBusinessNotebook class]],
        [FATField fieldWithIndex:16 type:TType_STRUCT optional:YES name:@"contact" valueType:TType_STRUCT valueClass:[EDAMUser class]],
        [FATField fieldWithIndex:17 type:TType_STRUCT optional:YES name:@"restrictions" valueType:TType_STRUCT valueClass:[EDAMNotebookRestrictions class]],
        [FATField fieldWithIndex:18 type:TType_STRUCT optional:YES name:@"recipientSettings" valueType:TType_STRUCT valueClass:[EDAMNotebookRecipientSettings class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMLinkedNotebook

+ (NSString *) structName {
  return @"LinkedNotebook";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"shareName"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"username"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"shardId"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"sharedNotebookGlobalId"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"uri"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:8 type:TType_I32 optional:YES name:@"updateSequenceNum"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"noteStoreUrl"],
        [FATField fieldWithIndex:10 type:TType_STRING optional:YES name:@"webApiUrlPrefix"],
        [FATField fieldWithIndex:11 type:TType_STRING optional:YES name:@"stack"],
        [FATField fieldWithIndex:12 type:TType_I32 optional:YES name:@"businessId"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNotebookDescriptor

+ (NSString *) structName {
  return @"NotebookDescriptor";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"guid"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"notebookDisplayName"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"contactName"],
        [FATField fieldWithIndex:4 type:TType_BOOL optional:YES name:@"hasSharedNotebook"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"joinedUserCount"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMUserProfile

+ (NSString *) structName {
  return @"UserProfile";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"id"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"name"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"email"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"username"],
        [FATField fieldWithIndex:5 type:TType_STRUCT optional:YES name:@"attributes" valueType:TType_STRUCT valueClass:[EDAMBusinessUserAttributes class]],
        [FATField fieldWithIndex:6 type:TType_I64 optional:YES name:@"joined"],
        [FATField fieldWithIndex:7 type:TType_I64 optional:YES name:@"photoLastUpdated"],
        [FATField fieldWithIndex:8 type:TType_STRING optional:YES name:@"photoUrl"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMRelatedContentImage

+ (NSString *) structName {
  return @"RelatedContentImage";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"url"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:YES name:@"width"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"height"],
        [FATField fieldWithIndex:4 type:TType_DOUBLE optional:YES name:@"pixelRatio"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"fileSize"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMRelatedContent

+ (NSString *) structName {
  return @"RelatedContent";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"contentId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"title"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"url"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"sourceId"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"sourceUrl"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"sourceFaviconUrl"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"sourceName"],
        [FATField fieldWithIndex:8 type:TType_I64 optional:YES name:@"date"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"teaser"],
        [FATField fieldWithIndex:10 type:TType_LIST optional:YES name:@"thumbnails" valueType:TType_STRUCT valueClass:[EDAMRelatedContentImage class]],
        [FATField fieldWithIndex:11 type:TType_I32 optional:YES name:@"contentType"],
        [FATField fieldWithIndex:12 type:TType_I32 optional:YES name:@"accessType"],
        [FATField fieldWithIndex:13 type:TType_STRING optional:YES name:@"visibleUrl"],
        [FATField fieldWithIndex:14 type:TType_STRING optional:YES name:@"clipUrl"],
        [FATField fieldWithIndex:15 type:TType_STRUCT optional:YES name:@"contact" valueType:TType_STRUCT valueClass:[EDAMContact class]],
        [FATField fieldWithIndex:16 type:TType_LIST optional:YES name:@"authors" valueType:TType_STRING valueClass:NULL],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBusinessInvitation

+ (NSString *) structName {
  return @"BusinessInvitation";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"businessId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"email"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"role"],
        [FATField fieldWithIndex:4 type:TType_I32 optional:YES name:@"status"],
        [FATField fieldWithIndex:5 type:TType_I32 optional:YES name:@"requesterId"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMUserIdentity

+ (NSString *) structName {
  return @"UserIdentity";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:YES name:@"type"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"stringIdentifier"],
        [FATField fieldWithIndex:3 type:TType_I64 optional:YES name:@"longIdentifier"],
    ];
  }
  return structFields;
}

@end

static NSString * EDAMCLASSIFICATION_RECIPE_USER_NON_RECIPE = @"000";
static NSString * EDAMCLASSIFICATION_RECIPE_USER_RECIPE = @"001";
static NSString * EDAMCLASSIFICATION_RECIPE_SERVICE_RECIPE = @"002";
static NSString * EDAMEDAM_NOTE_SOURCE_WEB_CLIP = @"web.clip";
static NSString * EDAMEDAM_NOTE_SOURCE_WEB_CLIP_SIMPLIFIED = @"Clearly";
static NSString * EDAMEDAM_NOTE_SOURCE_MAIL_CLIP = @"mail.clip";
static NSString * EDAMEDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = @"mail.smtp";

@implementation EDAMTypesConstants
+ (NSString *) CLASSIFICATION_RECIPE_USER_NON_RECIPE{
  return EDAMCLASSIFICATION_RECIPE_USER_NON_RECIPE;
}
+ (NSString *) CLASSIFICATION_RECIPE_USER_RECIPE{
  return EDAMCLASSIFICATION_RECIPE_USER_RECIPE;
}
+ (NSString *) CLASSIFICATION_RECIPE_SERVICE_RECIPE{
  return EDAMCLASSIFICATION_RECIPE_SERVICE_RECIPE;
}
+ (NSString *) EDAM_NOTE_SOURCE_WEB_CLIP{
  return EDAMEDAM_NOTE_SOURCE_WEB_CLIP;
}
+ (NSString *) EDAM_NOTE_SOURCE_WEB_CLIP_SIMPLIFIED{
  return EDAMEDAM_NOTE_SOURCE_WEB_CLIP_SIMPLIFIED;
}
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_CLIP{
  return EDAMEDAM_NOTE_SOURCE_MAIL_CLIP;
}
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY{
  return EDAMEDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
}
@end

