/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "ENTProtocol.h"
#import "ENTException.h"
#import "FATObject.h"

#import "EDAMAuthenticationTypes.h"

@implementation EDAMOpenIdCredential

+ (NSString *) structName {
  return @"OpenIdCredential";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"tokenPayload"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:NO name:@"serviceProvider"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMPlainCredential

+ (NSString *) structName {
  return @"PlainCredential";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"userId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"password"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAuthenticationRequestResult

+ (NSString *) structName {
  return @"AuthenticationRequestResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"userId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"userEmail"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:NO name:@"result"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMRegistrationRequestResult

+ (NSString *) structName {
  return @"RegistrationRequestResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"refreshToken"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"userEmail"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:NO name:@"result"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"name"],
    ];
  }
  return structFields;
}

@end


@implementation EDAMAuthenticationTypesConstants
@end

