/*
 * Copyright (c) 2017 by Evernote Corporation, All rights reserved.
 *
 * Use of the source code and binary libraries included in this package
 * is permitted under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "ENTProtocol.h"
#import "ENTException.h"
#import "FATObject.h"

#import "EDAMAuthenticationTypes.h"

@implementation EDAMOpenIdCredential

+ (NSString *) structName {
  return @"OpenIdCredential";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"tokenPayload"],
        [FATField fieldWithIndex:2 type:TType_I32 optional:NO name:@"serviceProvider"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMPlainCredential

+ (NSString *) structName {
  return @"PlainCredential";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"userId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"password"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAuthenticationRequestResult

+ (NSString *) structName {
  return @"AuthenticationRequestResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"userId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"userEmail"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:NO name:@"result"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMRegistrationRequestResult

+ (NSString *) structName {
  return @"RegistrationRequestResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"refreshToken"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"userEmail"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:NO name:@"result"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"name"],
    ];
  }
  return structFields;
}

@end


@implementation EDAMAuthenticationTypesConstants
@end

