/*
 * Copyright (c) 2015 by Evernote Corporation, All rights reserved.
 *
 * Use of the source code and binary libraries included in this package
 * is permitted under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "ENTProtocol.h"
#import "ENTException.h"
#import "FATObject.h"
#import "EDAMTypes.h"

#import "EDAMErrors.h"

@implementation EDAMUserException

+ (NSString *) structName {
  return @"EDAMUserException";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"errorCode"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"parameter"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMSystemException

+ (NSString *) structName {
  return @"EDAMSystemException";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"errorCode"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"message"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"rateLimitDuration"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMNotFoundException

+ (NSString *) structName {
  return @"EDAMNotFoundException";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"identifier"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"key"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMInvalidContactsException

+ (NSString *) structName {
  return @"EDAMInvalidContactsException";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_LIST optional:NO name:@"contacts" valueType:TType_STRUCT valueClass:[EDAMContact class]],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"parameter"],
        [FATField fieldWithIndex:3 type:TType_LIST optional:YES name:@"reasons" valueType:TType_I32 valueClass:NULL],
    ];
  }
  return structFields;
}

@end


@implementation ErrorsConstants
@end

