/*
 * Copyright (c) 2017 by Evernote Corporation, All rights reserved.
 *
 * Use of the source code and binary libraries included in this package
 * is permitted under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "ENTProtocol.h"
#import "ENTException.h"
#import "FATObject.h"
#import "EDAMTypes.h"
#import "EDAMErrors.h"
#import "EDAMAuthenticationTypes.h"

#import "EDAMUserStore.h"

@implementation EDAMPublicUserInfo

+ (NSString *) structName {
  return @"PublicUserInfo";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"userId"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"shardId"],
        [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"privilege"],
        [FATField fieldWithIndex:7 type:TType_I32 optional:YES name:@"serviceLevel"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"username"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"noteStoreUrl"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"webApiUrlPrefix"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMUserUrls

+ (NSString *) structName {
  return @"UserUrls";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"noteStoreUrl"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"webApiUrlPrefix"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"userStoreUrl"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"utilityUrl"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"messageStoreUrl"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"userWebSocketUrl"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"communicationEngineUrl"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAuthenticationResult

+ (NSString *) structName {
  return @"AuthenticationResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_I64 optional:NO name:@"currentTime"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"authenticationToken"],
        [FATField fieldWithIndex:3 type:TType_I64 optional:NO name:@"expiration"],
        [FATField fieldWithIndex:4 type:TType_STRUCT optional:YES name:@"user" structClass:[EDAMUser class]],
        [FATField fieldWithIndex:5 type:TType_STRUCT optional:YES name:@"publicUserInfo" structClass:[EDAMPublicUserInfo class]],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"noteStoreUrl"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"webApiUrlPrefix"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"secondFactorRequired"],
        [FATField fieldWithIndex:9 type:TType_STRING optional:YES name:@"secondFactorDeliveryHint"],
        [FATField fieldWithIndex:10 type:TType_STRUCT optional:YES name:@"urls" structClass:[EDAMUserUrls class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBootstrapSettings

+ (NSString *) structName {
  return @"BootstrapSettings";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"serviceHost"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"marketingUrl"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"supportUrl"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"accountEmailDomain"],
        [FATField fieldWithIndex:14 type:TType_STRING optional:YES name:@"cardscanUrl"],
        [FATField fieldWithIndex:15 type:TType_STRING optional:YES name:@"announcementsUrl"],
        [FATField fieldWithIndex:5 type:TType_BOOL optional:YES name:@"enableFacebookSharing"],
        [FATField fieldWithIndex:6 type:TType_BOOL optional:YES name:@"enableGiftSubscriptions"],
        [FATField fieldWithIndex:7 type:TType_BOOL optional:YES name:@"enableSupportTickets"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"enableSharedNotebooks"],
        [FATField fieldWithIndex:9 type:TType_BOOL optional:YES name:@"enableSingleNoteSharing"],
        [FATField fieldWithIndex:10 type:TType_BOOL optional:YES name:@"enableSponsoredAccounts"],
        [FATField fieldWithIndex:11 type:TType_BOOL optional:YES name:@"enableTwitterSharing"],
        [FATField fieldWithIndex:12 type:TType_BOOL optional:YES name:@"enableLinkedInSharing"],
        [FATField fieldWithIndex:13 type:TType_BOOL optional:YES name:@"enablePublicNotebooks"],
        [FATField fieldWithIndex:16 type:TType_BOOL optional:YES name:@"enableGoogle"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBootstrapProfile

+ (NSString *) structName {
  return @"BootstrapProfile";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"name"],
        [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"settings" structClass:[EDAMBootstrapSettings class]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMBootstrapInfo

+ (NSString *) structName {
  return @"BootstrapInfo";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_LIST optional:NO name:@"profiles" valueField:[FATField fieldWithIndex:0 type:TType_STRUCT optional:YES name:nil structClass:[EDAMBootstrapProfile class]]],
    ];
  }
  return structFields;
}

@end

@implementation EDAMPushNotificationCredentials

+ (NSString *) structName {
  return @"PushNotificationCredentials";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BINARY optional:NO name:@"iosDeviceToken"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"gcmRegistrationId"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMRegisterForSyncPushNotificationsResult

+ (NSString *) structName {
  return @"RegisterForSyncPushNotificationsResult";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_BINARY optional:YES name:@"sharedSecret"],
    ];
  }
  return structFields;
}

@end

@implementation EDAMAuthenticationParameters

+ (NSString *) structName {
  return @"AuthenticationParameters";
}

+ (NSArray *) structFields {
  static NSArray *structFields = nil;
  if (structFields == nil)
  {
    structFields = @[
        [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"usernameOrEmail"],
        [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"password"],
        [FATField fieldWithIndex:3 type:TType_STRING optional:YES name:@"ssoLoginToken"],
        [FATField fieldWithIndex:4 type:TType_STRING optional:YES name:@"consumerKey"],
        [FATField fieldWithIndex:5 type:TType_STRING optional:YES name:@"consumerSecret"],
        [FATField fieldWithIndex:6 type:TType_STRING optional:YES name:@"deviceIdentifier"],
        [FATField fieldWithIndex:7 type:TType_STRING optional:YES name:@"deviceDescription"],
        [FATField fieldWithIndex:8 type:TType_BOOL optional:YES name:@"supportsTwoFactor"],
        [FATField fieldWithIndex:9 type:TType_BOOL optional:YES name:@"supportsBusinessOnlyAccounts"],
    ];
  }
  return structFields;
}

@end

static int16_t EDAMEDAM_VERSION_MAJOR = 1;
static int16_t EDAMEDAM_VERSION_MINOR = 28;

@implementation EDAMUserStoreConstants
+ (int16_t) EDAM_VERSION_MAJOR{
  return EDAMEDAM_VERSION_MAJOR;
}
+ (int16_t) EDAM_VERSION_MINOR{
  return EDAMEDAM_VERSION_MINOR;
}
@end

@implementation EDAMUserStoreClient
- (instancetype) initWithProtocol: (id <ENTProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (instancetype) initWithInProtocol: (id <ENTProtocol>) anInProtocol outProtocol: (id <ENTProtocol>) anOutProtocol
{
  self = [super init];
  if (self != nil)  {
    _inProtocol = anInProtocol;
    _outProtocol = anOutProtocol;
  }
  return self;
}

- (BOOL) checkVersion: (NSString *) clientName edamVersionMajor: (int16_t) edamVersionMajor edamVersionMinor: (int16_t) edamVersionMinor
{
  [ENTProtocolUtil sendMessage:@"checkVersion"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"clientName"] value: clientName],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_I16 optional:NO name:@"edamVersionMajor"] value: @(edamVersionMajor)],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_I16 optional:NO name:@"edamVersionMinor"] value: @(edamVersionMinor)],
                            ]];

  return [[ENTProtocolUtil readMessage:@"checkVersion"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_BOOL optional:NO name:@"success"],
                              ]] boolValue];
}

- (EDAMBootstrapInfo *) getBootstrapInfo: (NSString *) locale
{
  [ENTProtocolUtil sendMessage:@"getBootstrapInfo"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"locale"] value: locale],
                            ]];

  return [ENTProtocolUtil readMessage:@"getBootstrapInfo"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMBootstrapInfo class]],
                              ]];
}

- (EDAMAuthenticationResult *) authenticate: (NSString *) username password: (NSString *) password consumerKey: (NSString *) consumerKey consumerSecret: (NSString *) consumerSecret supportsTwoFactor: (BOOL) supportsTwoFactor
{
  [ENTProtocolUtil sendMessage:@"authenticate"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"username"] value: username],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"password"] value: password],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"consumerKey"] value: consumerKey],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"consumerSecret"] value: consumerSecret],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:5 type:TType_BOOL optional:NO name:@"supportsTwoFactor"] value: @(supportsTwoFactor)],
                            ]];

  return [ENTProtocolUtil readMessage:@"authenticate"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) authenticateOpenID: (EDAMOpenIdCredential *) credential consumerKey: (NSString *) consumerKey consumerSecret: (NSString *) consumerSecret deviceIdentifier: (NSString *) deviceIdentifier deviceDescription: (NSString *) deviceDescription authLongSession: (BOOL) authLongSession supportsTwoFactor: (BOOL) supportsTwoFactor
{
  [ENTProtocolUtil sendMessage:@"authenticateOpenID"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"credential" structClass:[EDAMOpenIdCredential class]] value: credential],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"consumerKey"] value: consumerKey],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"consumerSecret"] value: consumerSecret],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"deviceIdentifier"] value: deviceIdentifier],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:5 type:TType_STRING optional:NO name:@"deviceDescription"] value: deviceDescription],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:6 type:TType_BOOL optional:NO name:@"authLongSession"] value: @(authLongSession)],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:7 type:TType_BOOL optional:NO name:@"supportsTwoFactor"] value: @(supportsTwoFactor)],
                            ]];

  return [ENTProtocolUtil readMessage:@"authenticateOpenID"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) authenticateLongSession: (NSString *) username password: (NSString *) password consumerKey: (NSString *) consumerKey consumerSecret: (NSString *) consumerSecret deviceIdentifier: (NSString *) deviceIdentifier deviceDescription: (NSString *) deviceDescription supportsTwoFactor: (BOOL) supportsTwoFactor
{
  [ENTProtocolUtil sendMessage:@"authenticateLongSession"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"username"] value: username],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"password"] value: password],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"consumerKey"] value: consumerKey],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"consumerSecret"] value: consumerSecret],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:5 type:TType_STRING optional:NO name:@"deviceIdentifier"] value: deviceIdentifier],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:6 type:TType_STRING optional:NO name:@"deviceDescription"] value: deviceDescription],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:7 type:TType_BOOL optional:NO name:@"supportsTwoFactor"] value: @(supportsTwoFactor)],
                            ]];

  return [ENTProtocolUtil readMessage:@"authenticateLongSession"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) authenticateLongSessionV2: (EDAMAuthenticationParameters *) authParams
{
  [ENTProtocolUtil sendMessage:@"authenticateLongSessionV2"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"authParams" structClass:[EDAMAuthenticationParameters class]] value: authParams],
                            ]];

  return [ENTProtocolUtil readMessage:@"authenticateLongSessionV2"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) completeTwoFactorAuthentication: (NSString *) authenticationToken oneTimeCode: (NSString *) oneTimeCode deviceIdentifier: (NSString *) deviceIdentifier deviceDescription: (NSString *) deviceDescription
{
  [ENTProtocolUtil sendMessage:@"completeTwoFactorAuthentication"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"oneTimeCode"] value: oneTimeCode],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"deviceIdentifier"] value: deviceIdentifier],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:4 type:TType_STRING optional:NO name:@"deviceDescription"] value: deviceDescription],
                            ]];

  return [ENTProtocolUtil readMessage:@"completeTwoFactorAuthentication"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (void) revokeLongSession: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"revokeLongSession"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

[ENTProtocolUtil readMessage:@"revokeLongSession"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) authenticateToBusiness: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"authenticateToBusiness"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"authenticateToBusiness"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMAuthenticationResult *) refreshAuthentication: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"refreshAuthentication"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"refreshAuthentication"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAuthenticationResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMUser *) getUser: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"getUser"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"getUser"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMUser class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMPublicUserInfo *) getPublicUserInfo: (NSString *) username
{
  [ENTProtocolUtil sendMessage:@"getPublicUserInfo"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"username"] value: username],
                            ]];

  return [ENTProtocolUtil readMessage:@"getPublicUserInfo"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMPublicUserInfo class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              ]];
}

- (EDAMPremiumInfo *) getPremiumInfo: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"getPremiumInfo"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"getPremiumInfo"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMPremiumInfo class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMSubscriptionInfo *) getSubscriptionInfo: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"getSubscriptionInfo"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"getSubscriptionInfo"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMSubscriptionInfo class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (NSString *) getNoteStoreUrl: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"getNoteStoreUrl"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"getNoteStoreUrl"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRING optional:NO name:@"success"],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMUserUrls *) getUserUrls: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"getUserUrls"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"getUserUrls"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMUserUrls class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (void) inviteToBusiness: (NSString *) authenticationToken emailAddress: (NSString *) emailAddress
{
  [ENTProtocolUtil sendMessage:@"inviteToBusiness"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"emailAddress"] value: emailAddress],
                            ]];

[ENTProtocolUtil readMessage:@"inviteToBusiness"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (void) removeFromBusiness: (NSString *) authenticationToken emailAddress: (NSString *) emailAddress
{
  [ENTProtocolUtil sendMessage:@"removeFromBusiness"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"emailAddress"] value: emailAddress],
                            ]];

[ENTProtocolUtil readMessage:@"removeFromBusiness"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              ]];
}

- (void) updateBusinessUserIdentifier: (NSString *) authenticationToken oldEmailAddress: (NSString *) oldEmailAddress newEmailAddress: (NSString *) newEmailAddress
{
  [ENTProtocolUtil sendMessage:@"updateBusinessUserIdentifier"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRING optional:NO name:@"oldEmailAddress"] value: oldEmailAddress],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:3 type:TType_STRING optional:NO name:@"newEmailAddress"] value: newEmailAddress],
                            ]];

[ENTProtocolUtil readMessage:@"updateBusinessUserIdentifier"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              ]];
}

- (NSArray<EDAMUserProfile *> *) listBusinessUsers: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"listBusinessUsers"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"listBusinessUsers"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_LIST optional:NO name:@"success" valueField:[FATField fieldWithIndex:0 type:TType_STRUCT optional:YES name:nil structClass:[EDAMUserProfile class]]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (NSArray<EDAMBusinessInvitation *> *) listBusinessInvitations: (NSString *) authenticationToken includeRequestedInvitations: (BOOL) includeRequestedInvitations
{
  [ENTProtocolUtil sendMessage:@"listBusinessInvitations"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_BOOL optional:NO name:@"includeRequestedInvitations"] value: @(includeRequestedInvitations)],
                            ]];

  return [ENTProtocolUtil readMessage:@"listBusinessInvitations"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_LIST optional:NO name:@"success" valueField:[FATField fieldWithIndex:0 type:TType_STRUCT optional:YES name:nil structClass:[EDAMBusinessInvitation class]]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

- (EDAMRegisterForSyncPushNotificationsResult *) registerForSyncPushNotifications: (NSString *) authenticationToken credentials: (EDAMPushNotificationCredentials *) credentials
{
  [ENTProtocolUtil sendMessage:@"registerForSyncPushNotifications"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"credentials" structClass:[EDAMPushNotificationCredentials class]] value: credentials],
                            ]];

  return [ENTProtocolUtil readMessage:@"registerForSyncPushNotifications"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMRegisterForSyncPushNotificationsResult class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              ]];
}

- (void) unregisterForSyncPushNotifications: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"unregisterForSyncPushNotifications"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

[ENTProtocolUtil readMessage:@"unregisterForSyncPushNotifications"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              ]];
}

- (NSString *) createSessionAuthenticationToken: (NSString *) authenticationToken
{
  [ENTProtocolUtil sendMessage:@"createSessionAuthenticationToken"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                            ]];

  return [ENTProtocolUtil readMessage:@"createSessionAuthenticationToken"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRING optional:NO name:@"success"],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              [FATField fieldWithIndex:3 type:TType_STRUCT optional:NO name:@"notFoundException" structClass:[EDAMNotFoundException class]],
                              ]];
}

- (EDAMAccountLimits *) getAccountLimits: (int) serviceLevel
{
  [ENTProtocolUtil sendMessage:@"getAccountLimits"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"serviceLevel"] value: @(serviceLevel)],
                            ]];

  return [ENTProtocolUtil readMessage:@"getAccountLimits"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_STRUCT optional:NO name:@"success" structClass:[EDAMAccountLimits class]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              ]];
}

- (NSDictionary<NSNumber *,EDAMIdentity *> *) getConnectedIdentities: (NSString *) authenticationToken identityIds: (NSArray<NSNumber *> *) identityIds
{
  [ENTProtocolUtil sendMessage:@"getConnectedIdentities"
                  toProtocol:_outProtocol
               withArguments:@[
                               [FATArgument argumentWithField:[FATField fieldWithIndex:1 type:TType_STRING optional:NO name:@"authenticationToken"] value: authenticationToken],
                               [FATArgument argumentWithField:[FATField fieldWithIndex:2 type:TType_LIST optional:NO name:@"identityIds" valueField:[FATField fieldWithIndex:0 type:TType_I64 optional:YES name:nil]] value: identityIds],
                            ]];

  return [ENTProtocolUtil readMessage:@"getConnectedIdentities"
                       fromProtocol:_inProtocol
                  withResponseTypes:@[
                              [FATField fieldWithIndex:0 type:TType_MAP optional:NO name:@"success" keyField:[FATField fieldWithIndex:0 type:TType_I64 optional:YES name:nil] valueField:[FATField fieldWithIndex:0 type:TType_STRUCT optional:YES name:nil structClass:[EDAMIdentity class]]],
                              [FATField fieldWithIndex:1 type:TType_STRUCT optional:NO name:@"userException" structClass:[EDAMUserException class]],
                              [FATField fieldWithIndex:2 type:TType_STRUCT optional:NO name:@"systemException" structClass:[EDAMSystemException class]],
                              ]];
}

@end

